# Generated by Django 2.0.5 on 2018-05-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('ifsc', models.TextField(primary_key=True, serialize=False)),
                ('branch', models.TextField()),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('district', models.TextField()),
                ('state', models.TextField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Banks', to='banks.Banks')),
            ],
        ),
    ]
